accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),  # 회원 가입
    path('delete/', views.delete, name='delete'),  # 회원 탈퇴
    path('update/', views.update, name='update'),  # 회원정보 수정
    path('password/', views.change_password, name='change_password'),  # 비밀번호 수정
    path('login/', views.login, name='login'),  # 로그인
    path('logout/', views.logout, name='logout'),  # 로그아웃
    path('<int:pk>/', views.profile, name='profile'),  # 프로필
]

duties/urls.py
from django.urls import path
from . import views

app_name = 'duties'
urlpatterns = [
    path('', views.index, name='index'), # 달력
    path('new/', views.event, name="new"), # 달력 리뉴얼
    path('dutylist/', views.dutylist, name='dutylist'),
    path('edit/<int:event_id>', views.event, name="edit"),
    path('test/', views.test, name='test'),
]

duty_table_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('duties/', include('duties.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    username = models.EmailField(unique=True)

    # 인적 사항: 이름, 나이, 사진
    name = models.CharField(max_length=100)
    age = models.DateField()
    photo = models.ImageField(upload_to='images/', blank=True)

    # 인사 정보: 사원 번호, 입사 연도, 직급, 소속팀
    emp_id = models.CharField(max_length=100, unique=True)
    emp_date = models.DateField()
    emp_grade = models.CharField(max_length=10)
    emp_team = models.CharField(max_length=10)

    REQUIRED_FIELDS = ['name', 'age', 'emp_id', 'emp_date', 'emp_grade', 'emp_team']

    def __str__(self):
        return f'{self.name} 사원'  # "박상현 사원"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext, gettext_lazy as _

class DateInput(forms.DateInput):
    input_type = 'date'


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'name', 'age', 'emp_id', 'emp_date', 'emp_grade', 'emp_team',)
        GRADE_CHOICES = (
            ('leader', 'leader'),   # 첫번째가 value
            ('follower', 'follower')
        )
        widgets = {
            'emp_date': DateInput(),
            'age' : DateInput(),
            'emp_grade' : forms.Select(choices=GRADE_CHOICES)
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('name', 'photo', 'emp_team',)


class CustomPasswordChangeForm(PasswordChangeForm):
        
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
    )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth import (
    login as auth_login, logout as auth_logout,
    get_user_model, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm

# SIGN UP: 회원가입
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('duties:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('duties:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


# DELETE: 회원 탈퇴
@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete() 
        auth_logout(request) 
    return redirect('duties:index')


# UPDATE: 회원정보 수정
@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('duties:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


# PASSWORD: 비밀번호 수정
@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('duties:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


# LOGIN: 로그인
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('duties:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'duties:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


# LOGOUT: 로그아웃
@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('duties:index')


# PROFILE: 프로필
@login_required
@require_safe
def profile(request, pk):
    worker = get_object_or_404(get_user_model(), pk=pk)
    context = {
        'worker': worker,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
  <header>
    <p class="display-6 fw-bold text-center title">Accounts Password Update Page</p>
  </header>

  <hr class="my-5">

  <section>
    <form action="{% url 'accounts:change_password' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% comment %} {{ form.as_p }} {% endcomment %}
      <div class="d-flex justify-content-end mt-5">
        <a id="update-btn" class="btn btn-outline-success mx-2 fw-bold" href="{% url 'accounts:profile' user.pk %}" role="button">뒤로 가기</a>
        <button id="account-btn" class="btn btn-outline-primary fw-bold" type="submit">확인</button>
      </div>
    </form>
  </section>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
  <header>
    <p class="display-6 text-center fw-bold title">Login Page</p>

    <div class="d-flex justify-content-end">
      {% if request.user.is_authenticated %}
      {% else %}
        <p><a id="account-btn" class="btn btn-outline-primary fw-bold" href="{% url 'accounts:signup' %}" role="button">회원 가입</a></P>
      {% endif %}
    </div>
  </header>

  <hr class="mt-3 mb-5">
  
  <section>
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex justify-content-end mt-5">
        <button id="update-btn" class="btn btn-outline-primary fw-bold" type="submit">확인</button>
      </div>
    </form>
  </section>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}  

  <header>
    <p class="display-6 fw-bold text-center title">Profile</p>

    <div class="d-flex justify-content-end">
      <p><a id="account-btn" class="btn btn-outline-success fw-bold" href="{% url 'accounts:update' %}" role="button">회원정보 수정</a></P>

      <p><a id="update-btn" class="btn btn-outline-success fw-bold mx-2" href="{% url 'duties:index' %}" role="button">뒤로 가기</a></P>
    </div>
  </header>

  <hr class="mt-3 mb-5">

  <section class="mx-auto mb-0 p-1 card" style="width: 50rem; height: 25rem;">
    <div class="row">
      <div class="col-md-5">
        <img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMjBfMjU5/MDAxNTc5NDY4NzQ2OTA2.45inocdoeaT5D6hAS-0LFCWHEHCCGsBEXPrY7fBPVAAg.Z24pQoPjt4alydbZpwoKXqZwm3CQafTOZP3nZL0DEMIg.JPEG.skil666/IMG_20190903_002601.jpg?type=w800" class="img-fluid rounded" alt="sample">
      </div>
      
      <div class="col-md-7" id="update-parent">
        <div class="card-body p-5">
          <p class="card-title fs-3 fw-bold mb-3">{{ user.name }}의 Profile</p>
          <div class="pt-5">
            <div class="d-inline-flex">
              <i class="fas fa-check mx-1 mt-1 d-inline-flex">
              </i>
              <h5 class="mb-3 mx-3">{{ user.emp_team }} 팀</h5>
            </div>
            <br>
            <div class="d-inline-flex">
              <i class="fas fa-check mx-1 mt-1">
              </i>
              <h5 class="mb-3 mx-3">사원번호: {{ user.emp_id }}</h5>
            </div>
            <br>
            <div class="d-inline-flex">
              <i class="fas fa-check mx-1 mt-1">
              </i>
              <h5 class="mb-3 mx-3">입사일: {{ user.emp_date }}</h5>
            </div>
            <div class="d-inline-flex">
              <i class="fas fa-check mx-1 mt-1">
              </i>
              <h5 class="mb-3 mx-3">직급: {{ user.emp_grade }}</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}



        <form action="{% url 'accounts:delete' %}" method="POST" class="ms-2">
          {% csrf_token %}
          <button class="btn btn-outline-danger" type="submit">회원 탈퇴</button>
        </form>

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
  <header>
    <p class="display-6 text-center fw-bold title">Signup Page</p>
  </header>

  <hr class="my-5">

  <section class="mb-5">
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex justify-content-end">
        <a id="update-btn" class="btn btn-outline-success mx-2" href="{% url 'duties:index' %}" role="button">BACK</a>
        <button id="update-btn" class="btn btn-outline-primary fw-bold" type="submit">확인</button>
      </div>
    </form>
  </section>
{% endblock content %}

accounts/templates/accounts/test.html
{% extends 'base.html' %}

{% block content %}
  <p>I'm a leader</p>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
  <header>
    <p class="display-6 text-center fw-bold title">Accounts Update Page</p>

    <div class="d-flex justify-content-end">
      <form action="{% url 'accounts:delete' %}" method="POS">
        <button id="account-btn" class="btn btn-outline-danger fw-bold" type="submit">회원 탈퇴</button>
      </form>
    </div>
  </header>
  
  <hr class="mt-3 mb-5">

  <section>
    <form action="{% url 'accounts:update' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% comment %} {{ form.as_p }} {% endcomment %}
      <div class="d-flex justify-content-end">
        <a id="update-btn" class="btn btn-outline-success mx-2 fw-bold" href="{% url 'accounts:profile' user.pk %}" role="button">뒤로 가기</a>
        <button id="account-btn" class="btn btn-outline-primary fw-bold" type="submit">확인</button>
      </div>
    </form>
  </section>
{% endblock content %}