articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),  # community service의 main page -- 블라인드 참고
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

duties/urls.py
from django.urls import path
from . import views

app_name = 'duties'
urlpatterns = [
    path('', views.index, name='index'), # 달력
    path('new/', views.event, name="new"), # 달력 리뉴얼
    path('dutylist/', views.dutylist, name='dutylist'),
    path('edit/<int:event_id>', views.event, name="edit"),
    path('test/', views.test, name='test'),
]

duty_table_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('duties/', include('duties.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Article(models.Model):
    CAT_WORK = 'wk'
    CAT_LIFE = 'lf'
    CAT_FINANCE = 'fn'
    CAT_QUESTION = 'qt'
    CATEGORY_CHOICES = [
        (CAT_WORK, '근무 이야기'),
        (CAT_LIFE, '일상 이야기'),
        (CAT_FINANCE, '머니 이야기'),
        (CAT_QUESTION, '질문 이야기'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=30)
    content = models.TextField()
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=CAT_WORK)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'mt-2 form-control',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'mt-2 form-control',
            }
        )
    )
    category = forms.ChoiceField(
        label='종류',
        choices=Article.CATEGORY_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'mt-2 form-select',
            }
        )
    )

    class Meta:
        model = Article
        exclude = ('user', 'like_users',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': '1',
            }
        )
    )

    class Meta:
        model = Comment
        exclude = ('article', 'user',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


@login_required
@require_safe
def index(request):
    articles = Article.objects.order_by('-pk')
    
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@login_required
@require_safe
def detail(request, pk):
    fake_user_id = list(range(0, 1001))

    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
        'fake_user_id': fake_user_id,
    }
    return render(request, 'articles/detail.html', context)


@login_required
@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user.is_authenticated:
        if request.user == article.user: 
            article.delete()
            return redirect('articles:index')
    return 


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def create_comments(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:detail', article.pk)
    return redirect('accounts:login')


@require_POST
def delete_comments(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


@require_POST
def likes(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)

        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            is_like = False
        else:
            article.like_users.add(request.user)
            is_like = True
        context = {
            'is_like': is_like,
            'count_like': article.like_users.count(),
        }
        return JsonResponse(context)
    return HttpResponse(status=401)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  {# header #}
  <header>
    {# title #}
    <p class="display-5 text-center fw-bold title">한마디 하기</p>
  </header>

  <hr class="mt-4 mb-5">
  
  {# body #}
  <section>
    <form action="{% url 'articles:create' %}" method="POST">
      {% csrf_token %}
        <p class="mb-4">
          {{ form.category.errors }}
          {{ form.category.label_tag }}
          {{ form.category }}
        </p>
        <p class="mb-4">
          {{ form.title.errors }}
          {{ form.title.label_tag }}
          {{ form.title }}
        </p>
        <p class="mb-4">
          {{ form.content.errors }}
          {{ form.content.label_tag }}
          {{ form.content }}
        </p>

      {# nav buttons #}
      <div class="d-flex justify-content-end">
        <a id="update-btn" href="{% url 'articles:index' %}" role="button" class="mx-2 btn btn-outline-dark fw-bold">뒤로 가기</a>
        <button id="account-btn" class="btn btn-outline-success fw-bold" type="submit">한마디 투척</button>
      </div>
    </form>
  </section>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <header>
    {# title #}
    <p class="display-5 text-center fw-bold title">속닥속닥</p>

    {# nav buttons #}
    <div class="d-flex justify-content-between align-items-center">
      <div>
        Category >
        {% if article.category == 'wk' %}
          <span class="badge bg-primary">근무 이야기</span>
        {% elif article.category == 'lf' %}
          <span class="badge bg-success">일상 이야기</span>
        {% elif article.category == 'fn' %}
          <span class="badge bg-danger">머니 이야기</span>
        {% elif article.category == 'qt' %}
          <span class="badge bg-warning">질문 이야기</span>
        {% endif %}
      </div>

      <div class="d-flex justify-content-end">
        {% if user == article.user %}
          <a id="account-btn" href="{% url 'articles:update' article.pk %}" role="button" class="btn btn-outline-success fw-bold">말조심하기</a>
          <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <button id="account-btn" class="mx-2 btn btn-outline-danger fw-bold" type="submit">말 주워 담기</button>
          </form>
        {% endif %}
        <a id="update-btn" href="{% url 'articles:index' %}" role="button" class="btn btn-outline-dark fw-bold">뒤로 가기</a>
      </div>
    </div>
  </header>

  <hr class="mb-5">

  <section class="container mb-5">
    <div class="mb-4">
      <div class="d-flex align-items-center mb-1">
        <p class="mb-0 me-2 fs-3 fw-bold">{{ article.title }}</p>

        {# like button #}
        <form id="form-like" data-article-id="{{ article.pk }}" class="d-inline">
          {% csrf_token %}
          {% if user in article.like_users.all %}
            <button class="btn btn-outline-danger" type="submit">
              <i id="img-like-{{ article.pk }}" class="bi bi-heart text-danger"></i>
            </button>
          {% else %}
            <button class="btn btn-outline-danger" type="submit">
              <i id="img-like-{{ article.pk }}" class="bi bi-heart-fill text-danger"></i>
            </button>
          {% endif %}
        </form>
      </div>

      <div class="d-flex justify-content-between align-items-center">
        <p class="mb-0 fw-light">{{ article.updated_at|date:"Y. m. d. H:i" }}</p>
        <p class="mb-0">
          {# like img and count #}
          <span><i class="me-1 bi bi-heart text-danger"></i></span>
          <span id="count-like-{{ article.pk }}">{{ article.like_users.all|length }}</span>

          {# comment img and count #}
          <span><i class="ms-3 me-1 bi bi-chat-left-dots"></i></span>
          <span id="comment-count-title">{{ article.comment_set.all|length }}</span>
        </p>
      </div>
    </div>

    <div class="p-3 border border-2 rounded" style="margin-bottom: 100px;">
      {{ article.content }}
    </div>

    <div class="mb-5">
      <p>댓글: <span id="comment-count-body">{{ article.comment_set.all|length }}</span></p>
      <form action="{% url 'articles:create_comments' article.pk %}" method="POST">
        {% csrf_token %}
        <div class="row">
          <p class="mb-0 col-10">
            {{ comment_form.content.errors }}
            {{ comment_form.content }}
          </p>
          <button id="account-btn" class="col btn btn-outline-success fw-bold" type="submit">대꾸하기</button>
        </div>
      </form>
    </div>

    <hr>

    <div>
      {% for comment in comments %}
        <div class="d-flex justify-content-between align-items-center mb-2">
          <p class="ms-2 mb-0">
            <span><i class="bi bi-emoji-smile"></i> 익명의 {{ fake_user_id|random }}번째 누군가:</span> 
            <span class="fw-bold">{{ comment }}</span>
          </p>

          {% if user == comment.user %}
            <form action="{% url 'articles:delete_comments' article.pk comment.pk %}" method="POST" class="d-inline">
              {% csrf_token %}
              <button class="btn btn-outline-danger" type="submit"><i class="bi bi-x-lg"></i></button>
            </form>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock content %}

{% block script %}
  <script>
    const formLike = document.querySelector('#form-like')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    formLike.addEventListener('submit', function (event) {
      event.preventDefault()

      const articleId = event.target.dataset.articleId

      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/articles/${articleId}/likes/`,
        headers: {'X-CSRFToken': csrftoken}
      })
        .then(response => {
          const {is_like, count_like} = response.data

          const imgLike = document.querySelector(`#img-like-${articleId}`)
          const countLike = document.querySelector(`#count-like-${articleId}`)

          is_like ? imgLike.setAttribute('class', 'bi bi-heart-fill text-danger') : imgLike.setAttribute('class', 'bi bi-heart text-danger')
          countLike.innerText = count_like
        })
        .catch(error => {
          console.log(error.response)
          if (error.response.status === 401) {
            console.log(window.location.href)
            window.location.href = `http://127.0.0.1:8000/accounts/login/`
          }
        })
    })
  </script>
{% endblock script %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {# header #}
  <header>
    {# title #}
    <p class="display-5 text-center fw-bold title">속닥속닥</p>

    {# nav buttons #}
    <div class="d-flex justify-content-end">
      <a id="update-btn" href="{% url 'duties:index' %}" role="button" class="mx-2 btn btn-outline-dark fw-bold">
        <i class="me-1 bi bi-calendar-check"></i>
        <span>캘린더 보기</span>
      </a>
      <a id="account-btn" href="{% url 'articles:create' %}" role="button" class="btn btn-outline-primary fw-bold">
        <i class="me-1 bi bi-pen"></i>
        <span>한마디 하기</span>
      </a>
    </div>
  </header>

  <hr class="mb-5">

  {# body #}
  <section class="row mb-5">
    {# articles #}
    <section class="col-9 me-2">
      <ul class="list-group">
        {% for article in articles %}
          <li class="list-group-item">
            <div class="d-flex justify-content-between my-2">
              {# front #}
              <div class="d-flex align-items-center">
                {# category #}
                {% if article.category == 'wk' %}
                  <span class="badge bg-primary">근무 이야기</span>
                {% elif article.category == 'lf' %}
                  <span class="badge bg-success">일상 이야기</span>
                {% elif article.category == 'fn' %}
                  <span class="badge bg-danger">머니 이야기</span>
                {% elif article.category == 'qt' %}
                  <span class="badge bg-warning">질문 이야기</span>
                {% endif %}
                
                {# title #}
                <a href="{% url 'articles:detail' article.pk %}" class="text-decoration-none text-dark ms-3 fs-6">
                  {{ article.title }}
                </a>
              </div>

              {# end #}
              <div class="d-flex align-items-center">
                {# like img and count #}
                <span><i class="me-2 bi bi-heart text-danger"></i></span>
                <span>{{ article.like_users.all|length }}</span>

                {# comment img and count #}
                <span><i class="ms-3 me-2 bi bi-chat-left-dots"></i></span>
                <span>{{ article.comment_set.all|length }}</span>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </section>
    
    {# ads #}
    <section class="col">
      <p>여기는 광고를 올릴 곳입니다.</p>
      <img src="{% static 'images/ads.sample.ssafy_textbook.jpeg' %}" alt="ads sample" class="img-fluid">
    </section>
  </section>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  {# header #}
  <header>
    {# title #}
    <p class="display-5 text-center fw-bold title">한마디 수정하기</p>
  </header>

  <hr class="my-5">
  
  {# body #}
  <section>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
      {% csrf_token %}
        <p class="mb-4">
          {{ form.category.errors }}
          {{ form.category.label_tag }}
          {{ form.category }}
        </p>
        <p class="mb-4">
          {{ form.title.errors }}
          {{ form.title.label_tag }}
          {{ form.title }}
        </p>
        <p class="mb-4">
          {{ form.content.errors }}
          {{ form.content.label_tag }}
          {{ form.content }}
        </p>

      {# nav buttons #}
      <div class="d-flex justify-content-end">
        <a id="update-btn" href="{% url 'articles:index' %}" role="button" class="mx-2 btn btn-outline-dark fw-bold">뒤로 가기</a>
        <button id="account-btn" class="btn btn-outline-success fw-bold" type="submit">다시 투척</button>
      </div>
    </form>
  </section>
{% endblock content %}